CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE TABLE ST(
	ST_ID uuid DEFAULT uuid_generate_v1mc() PRIMARY KEY,
	ST_NAME VARCHAR,
	ST BOOL DEFAULT TRUE,
	C_DATE TIMESTAMP WITH TIME ZONE DEFAULT TRANSACTION_TIMESTAMP(),
	U_DATE TIMESTAMP WITH TIME ZONE DEFAULT STATEMENT_TIMESTAMP(),
	IS_ACTIVE BOOL DEFAULT TRUE

);
CREATE TABLE USERS (
	USER_ID uuid DEFAULT uuid_generate_v1mc() PRIMARY KEY,
	NAME VARCHAR,
	SURNAME VARCHAR,
	USERNAME VARCHAR(30) UNIQUE,
	USER_PASSWORD VARCHAR NOT NULL,
	GENDER INT DEFAULT 0,
	EMAIL VARCHAR UNIQUE,
	PHONE_NUMBER VARCHAR UNIQUE,
	ADDRESS VARCHAR,	
	IS_VET BOOL DEFAULT FALSE,
	C_DATE TIMESTAMP WITH TIME ZONE DEFAULT TRANSACTION_TIMESTAMP(),
	U_DATE TIMESTAMP WITH TIME ZONE DEFAULT STATEMENT_TIMESTAMP(),
	ST_ID uuid REFERENCES ST (ST_ID),
	IS_ACTIVE BOOL DEFAULT TRUE
	
);

CREATE TABLE VET (
	VET_ID uuid DEFAULT uuid_generate_v1mc() PRIMARY KEY,
	USER_ID uuid REFERENCES USERS (USER_ID) UNIQUE,
	C_DATE TIMESTAMP WITH TIME ZONE DEFAULT TRANSACTION_TIMESTAMP(),
	U_DATE TIMESTAMP WITH TIME ZONE DEFAULT STATEMENT_TIMESTAMP(),
	ST_ID uuid REFERENCES ST (ST_ID),
	IS_ACTIVE BOOL DEFAULT TRUE
	
);
CREATE TABLE CLINIC (
	CLINIC_ID uuid DEFAULT uuid_generate_v1mc() PRIMARY KEY,
	OWNER_ID uuid  REFERENCES VET (VET_ID) UNIQUE,
	CLINIC_NAME VARCHAR UNIQUE,
	C_DATE TIMESTAMP WITH TIME ZONE DEFAULT TRANSACTION_TIMESTAMP(),
	U_DATE TIMESTAMP WITH TIME ZONE DEFAULT STATEMENT_TIMESTAMP(),
	ST_ID uuid REFERENCES ST (ST_ID),
	IS_ACTIVE BOOL DEFAULT TRUE
	
);
CREATE TABLE PET (
	PET_ID uuid DEFAULT uuid_generate_v1mc() PRIMARY KEY,
	VET_ID uuid  REFERENCES VET (VET_ID),
	OWNER_ID uuid  REFERENCES USERS (USER_ID),
	NAME VARCHAR,
	GENDER INT DEFAULT 0,
	PET_TYPE VARCHAR,
	PET_BREED VARCHAR,
	C_DATE TIMESTAMP WITH TIME ZONE DEFAULT TRANSACTION_TIMESTAMP(),
	U_DATE TIMESTAMP WITH TIME ZONE DEFAULT STATEMENT_TIMESTAMP(),
	ST_ID uuid REFERENCES ST (ST_ID),
	IS_ACTIVE BOOL DEFAULT TRUE
	
);
