CREATE TABLE CITY (
  CITY_ID  SERIAL PRIMARY KEY,
  CITY_NAME VARCHAR,
  C_DATE TIMESTAMP WITH TIME ZONE DEFAULT TRANSACTION_TIMESTAMP(),
  U_DATE TIMESTAMP WITH TIME ZONE DEFAULT STATEMENT_TIMESTAMP(),
  ST_ID uuid REFERENCES ST (ST_ID),
  IS_ACTIVE BOOL DEFAULT TRUE,
);
CREATE TABLE DISTRICT (
  DISTRICT_ID  SERIAL PRIMARY KEY,
  DISTRICT_NAME VARCHAR,
  CITY_ID SERIAL REFERENCES CITY (CITY_ID),
  C_DATE TIMESTAMP WITH TIME ZONE DEFAULT TRANSACTION_TIMESTAMP(),
  U_DATE TIMESTAMP WITH TIME ZONE DEFAULT STATEMENT_TIMESTAMP(),
  ST_ID uuid REFERENCES ST (ST_ID),
  IS_ACTIVE BOOL DEFAULT TRUE
);
CREATE TABLE STREETS (
    STREET_ID  SERIAL PRIMARY KEY,
    STREET_NAME VARCHAR,
    DISTRICT_ID SERIAL REFERENCES DISTRICTS (DISTRICT_ID),
	  C_DATE TIMESTAMP WITH TIME ZONE DEFAULT TRANSACTION_TIMESTAMP(),
	  U_DATE TIMESTAMP WITH TIME ZONE DEFAULT STATEMENT_TIMESTAMP(),
	  ST_ID uuid REFERENCES ST (ST_ID),
	  IS_ACTIVE BOOL DEFAULT TRUE
);
CREATE TABLE ADDRESS(
	ADDRESS_ID SERIAL PRIMARY KEY,
	ADDRESS_TITLE VARCHAR,
	ADDRESS_DESCRIPTION VARCHAR,
	DISTRICT_ID SERIAL REFERENCES DISTRICTS (DISTRICT_ID),
	CITY_ID SERIAL REFERENCES CITY (CITY_ID),
	STREET_ID SERIAL REFERENCES STREET (STREET_ID),
	USER_ID SERIAL REFERENCES USERS (USER_ID),
	C_DATE TIMESTAMP WITH TIME ZONE DEFAULT TRANSACTION_TIMESTAMP(),
	U_DATE TIMESTAMP WITH TIME ZONE DEFAULT STATEMENT_TIMESTAMP(),
	ST_ID uuid REFERENCES ST (ST_ID),
	IS_ACTIVE BOOL DEFAULT TRUE
);
ALTER TABLE USERS ADD COLUMN ADDRESS_ID SERIAL REFERENCES ADDRESS (ADDRESS_ID);
ALTER TABLE VET ADD COLUMN CITY_ID SERIAL REFERENCES CITY (CITY_ID);



INSERT INTO CITY (CITY_NAME) VALUES ('Adana');
INSERT INTO CITY (CITY_NAME) VALUES ('Adıyaman');
INSERT INTO CITY (CITY_NAME) VALUES ('Afyonkarahisar');
INSERT INTO CITY (CITY_NAME) VALUES ('Ağrı');
INSERT INTO CITY (CITY_NAME) VALUES ('Amasya');
INSERT INTO CITY (CITY_NAME) VALUES ('Ankara');
INSERT INTO CITY (CITY_NAME) VALUES ('Antalya');
INSERT INTO CITY (CITY_NAME) VALUES ('Artvin');
INSERT INTO CITY (CITY_NAME) VALUES ('Aydın');
INSERT INTO CITY (CITY_NAME) VALUES ('Balıkesir');
INSERT INTO CITY (CITY_NAME) VALUES ('Bilecik');
INSERT INTO CITY (CITY_NAME) VALUES ('Bingöl');
INSERT INTO CITY (CITY_NAME) VALUES ('Bitlis');
INSERT INTO CITY (CITY_NAME) VALUES ('Bolu');
INSERT INTO CITY (CITY_NAME) VALUES ('Burdur');
INSERT INTO CITY (CITY_NAME) VALUES ('Bursa');
INSERT INTO CITY (CITY_NAME) VALUES ('Çanakkale');
INSERT INTO CITY (CITY_NAME) VALUES ('Çankırı');
INSERT INTO CITY (CITY_NAME) VALUES ('Çorum');
INSERT INTO CITY (CITY_NAME) VALUES ('Denizli');
INSERT INTO CITY (CITY_NAME) VALUES ('Diyarbakır');
INSERT INTO CITY (CITY_NAME) VALUES ('Edirne');
INSERT INTO CITY (CITY_NAME) VALUES ('Elazığ');
INSERT INTO CITY (CITY_NAME) VALUES ('Erzincan');
INSERT INTO CITY (CITY_NAME) VALUES ('Erzurum');
INSERT INTO CITY (CITY_NAME) VALUES ('Eskişehir');
INSERT INTO CITY (CITY_NAME) VALUES ('Gaziantep');
INSERT INTO CITY (CITY_NAME) VALUES ('Giresun');
INSERT INTO CITY (CITY_NAME) VALUES ('Gümüşhane');
INSERT INTO CITY (CITY_NAME) VALUES ('Hakkari');
INSERT INTO CITY (CITY_NAME) VALUES ('Hatay');
INSERT INTO CITY (CITY_NAME) VALUES ('Isparta');
INSERT INTO CITY (CITY_NAME) VALUES ('Mersin');
INSERT INTO CITY (CITY_NAME) VALUES ('İstanbul');
INSERT INTO CITY (CITY_NAME) VALUES ('İzmir');
INSERT INTO CITY (CITY_NAME) VALUES ('Kars');
INSERT INTO CITY (CITY_NAME) VALUES ('Kastamonu');
INSERT INTO CITY (CITY_NAME) VALUES ('Kayseri');
INSERT INTO CITY (CITY_NAME) VALUES ('Kırklareli');
INSERT INTO CITY (CITY_NAME) VALUES ('Kırşehir');
INSERT INTO CITY (CITY_NAME) VALUES ('Kocaeli');
INSERT INTO CITY (CITY_NAME) VALUES ('Konya');
INSERT INTO CITY (CITY_NAME) VALUES ('Kütahya');
INSERT INTO CITY (CITY_NAME) VALUES ('Malatya');
INSERT INTO CITY (CITY_NAME) VALUES ('Manisa');
INSERT INTO CITY (CITY_NAME) VALUES ('Kahramanmaraş');
INSERT INTO CITY (CITY_NAME) VALUES ('Mardin');
INSERT INTO CITY (CITY_NAME) VALUES ('Muğla');
INSERT INTO CITY (CITY_NAME) VALUES ('Muş');
INSERT INTO CITY (CITY_NAME) VALUES ('Nevşehir');
INSERT INTO CITY (CITY_NAME) VALUES ('Niğde');
INSERT INTO CITY (CITY_NAME) VALUES ('Ordu');
INSERT INTO CITY (CITY_NAME) VALUES ('Rize');
INSERT INTO CITY (CITY_NAME) VALUES ('Sakarya');
INSERT INTO CITY (CITY_NAME) VALUES ('Samsun');
INSERT INTO CITY (CITY_NAME) VALUES ('Siirt');
INSERT INTO CITY (CITY_NAME) VALUES ('Sinop');
INSERT INTO CITY (CITY_NAME) VALUES ('Sivas');
INSERT INTO CITY (CITY_NAME) VALUES ('Tekirdağ');
INSERT INTO CITY (CITY_NAME) VALUES ('Tokat');
INSERT INTO CITY (CITY_NAME) VALUES ('Trabzon');
INSERT INTO CITY (CITY_NAME) VALUES ('Tunceli');
INSERT INTO CITY (CITY_NAME) VALUES ('Şanlıurfa');
INSERT INTO CITY (CITY_NAME) VALUES ('Uşak');
INSERT INTO CITY (CITY_NAME) VALUES ('Van');
INSERT INTO CITY (CITY_NAME) VALUES ('Yozgat');
INSERT INTO CITY (CITY_NAME) VALUES ('Zonguldak');
INSERT INTO CITY (CITY_NAME) VALUES ('Aksaray');
INSERT INTO CITY (CITY_NAME) VALUES ('Bayburt');
INSERT INTO CITY (CITY_NAME) VALUES ('Karaman');
INSERT INTO CITY (CITY_NAME) VALUES ('Kırıkkale');
INSERT INTO CITY (CITY_NAME) VALUES ('Batman');
INSERT INTO CITY (CITY_NAME) VALUES ('Şırnak');
INSERT INTO CITY (CITY_NAME) VALUES ('Bartın');
INSERT INTO CITY (CITY_NAME) VALUES ('Ardahan');
INSERT INTO CITY (CITY_NAME) VALUES ('Iğdır');
INSERT INTO CITY (CITY_NAME) VALUES ('Yalova');
INSERT INTO CITY (CITY_NAME) VALUES ('Karabük');
INSERT INTO CITY (CITY_NAME) VALUES ('Kilis');
INSERT INTO CITY (CITY_NAME) VALUES ('Osmaniye');
INSERT INTO CITY (CITY_NAME) VALUES ('Düzce');



